__author__ = 'Benjamin George Roberts <benjamin.roberts@anu.edu.au>'
from collections import defaultdict

EVENT_GLYPH_SET = defaultdict(lambda x: ('info', 'glyphicon-question-sign'))
__GLYPH_SET__ = {
    'application': ('glyphicon-heart', 'success'),
    'notice_filed': ('glyphicon-duplicate', 'info'),
    'grounds_statement_due': ('glyphicon-calendar', 'info'),
    'opi': ('glyphicon-education','success'),
    'acceptance_published': ('glyphicon-education', 'info'),
    'last_opposition_lodge': ('glyphicon-inbox', 'info'),
    'filing': ('glyphicon-duplicate', 'info'),
    'published': ('glyphicon-education', 'info'),
    'opposition_filed': ('glyphicon-duplicate', 'warning'),
    'earliest_priority': ('glyphicon-calendar', 'info'),
    'acceptance_receipt': ('glyphicon-edit', 'info'),
    'receipt_published': ('glyphicon-education', 'info'),
    'further_report_issue': ('glyphicon-retweet', 'info'),
    'tga_approval': ('glyphicon-apple','success'),
    'notice_served': ('glyphicon-envelope', 'warning'),
    'search_results_received': ('glyphicon-inbox', 'info'),
    'deferement_request': ('glyphicon-comment', 'primary'),
    'reply_evidence_served': ('glyphicon-envelope', 'info'),
    'exam_request_filing': ('glyphicon-folder-close', 'info'),
    'name_change': ('glyphicon-text-size','primary'),
    'opi_published_in_journal': ('glyphicon-education', 'info'),
    'intent_notice_due': ('glyphicon-calendar', 'info'),
    'grounds_statement_filed': ('glyphicon-duplicate', 'info'),
    'withdrawl': ('glyphicon-thumbs-down', 'danger'),
    'support_evidence_due': ('glyphicon-calendar', 'warning'),
    'reply_evidence_due': ('glyphicon-calendar','warning'),
    'intent_notice_served': ('glyphicon-envelope', 'info'),
    'answer_evidence_served': ('glyphicon-envelope', 'info'),
    'first_report_issue': ('glyphicon-retweet', 'info'),
    'extension_from': ('glyphicon-calendar','success'),
    'grant_published': ('glyphicon-education','success'),
    'answer_evidence_due': ('glyphicon-calendar','warning'),
    'acceptance_advertised': ('glyphicon-list-alt','success'),
    'support_evidence_served': ('glyphicon-envelope', 'info'),
    'support_evidence_filed': ('glyphicon-duplicate', 'info'),
    'third_prty_exam_requested': ('glyphicon-comment', 'info'),
    'search_completed': ('glyphicon-map-marker', 'info'),
    'sealed': ('glyphicon-pushpin','success'),
    'expiry': ('glyphicon-scissors', 'danger'),
    'withdrawl_published': ('glyphicon-education', 'danger'),
    'effective_patent': ('glyphicon-thumbs-up','primary'),
    'wipo_publication': ('glyphicon-education','success'),
    'request_filed': ('glyphicon-duplicate', 'info'),
    'exam_request': ('glyphicon-retweet', 'info'),
    'grounds_statement_served': ('glyphicon-envelope', 'info'),
    'asssignment_validated': ('glyphicon-certificate','success'),
    'application_receipt': ('glyphicon-edit', 'info'),
    'reply_evidence_filed': ('glyphicon-duplicate', 'info'),
    'intent_notice_filed': ('glyphicon-duplicate', 'info'),
    'application_filed': ('glyphicon-duplicate','success'),
    'journal_published': ('glyphicon-education','success'),
    'refusal': ('glyphicon-ban-circle', 'danger'),
    'advertised': ('glyphicon-eye-open', 'info'),
    'answer_evidence_filed': ('glyphicon-duplicate', 'info'),
    'opposition_decision': ('glyphicon-screenshot', 'danger'),
    'restoration': ('glyphicon-backward','success'),
    'applied': ('glyphicon-bell','success'),
    'continue_renew_fee_paid': ('glyphicon-piggy-bank', 'danger'),
    'certification': ('glyphicon-check','success'),
    'application_published': ('glyphicon-education', 'info'),
    'in_force_to': ('glyphicon-check','primary'),
    'refusal_published': ('glyphicon-education', 'danger'),
    'npe': ('glyphicon-hand-up','success'),
    'decision_issued': ('glyphicon-info-sign','warning'),
    'hearing': ('glyphicon-cd','warning'),
    'granted': ('glyphicon-ok-circle', 'success'),
}

for k,v in __GLYPH_SET__.items():
    EVENT_GLYPH_SET[k] = v
